# Generated by Django 4.0.5 on 2022-07-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='massage',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='discriptions',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
